import gspread  # Module needed for google sheets.
from oauth2client.service_account import ServiceAccountCredentials
# from pprint import pprint  # Print pretty messages.

# Get scope for google sheets.
scope = [
    "https://spreadsheets.google.com/feeds",
    'https://www.googleapis.com/auth/spreadsheets',
    "https://www.googleapis.com/auth/drive.file",
    "https://www.googleapis.com/auth/drive"]

# Credentials file from Google Cloud Console. This is generated by Google Drive
# API and allows Python to connect to your Google Drive.
# Make sure to add this file to gitignore.
creds = ServiceAccountCredentials.from_json_keyfile_name(
    "creds.json", scope
)

# Make a Google Sheets client and connect it to your Google Drive.
client = gspread.authorize(creds)

"""
sheet = client.open("pyEBOT test sheet").sheet1


data = sheet.get_all_records()

pprint(data)
"""

spreadSheet = client.open("EVENTS")
sheet = spreadSheet.worksheet('Discord Parsed Data')


# Functions
def getCell(rowIndex, colIndex):
    cell = sheet.cell(rowIndex, colIndex)
    return cell.value


def setCell(rowIndex, colIndex, value):
    sheet.update_cell(rowIndex, colIndex, value)


def getAll():
    return sheet.get_all_records()
    # TODO: Commented out to save on sheets api call return.
    # now returns dummy data. Revert to normal once testing is complete
    # dummyList = []
    # for i in range(5):
    #     data = {
    #         'Event': f'event{i}',
    #         'Date': f'date{i}',
    #         'Time': f'time{i}',
    #         'Description': f'description{i}',
    #         'Participants': f'participants{i}',
    #         'MessageId': f''}
    #     dummyList.append(data)
    # return dummyList


def getCol(index):
    return sheet.col_values(index)


def getRow(rowNum):
    data = sheet.row_values(rowNum)
    return data


# This must run periodically to avoid loosing authentication. Timeout is 1hr.
def refreshAuth():
    client.login()

# TODO: Encapsulate this code within a class to make it compatible with sphinx
# documentation.
